server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://order-service:8785;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Trace-Id $http_x_trace_id;
  }

  location / {
    try_files $uri /index.html;
  }
}

