server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://order-service:8785;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Trace-Id $http_x_trace_id;
  }

  location /ws/ {
    proxy_pass http://order-service:8785;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location /inventory-api/ {
    rewrite ^/inventory-api/(.*)$ /api/inventory/$1 break;
    proxy_pass http://inventory-service:8786;
  }

  location /payment-api/ {
    rewrite ^/payment-api/(.*)$ /api/payments/$1 break;
    proxy_pass http://payment-service:8787;
  }

  location /inventory-health {
    proxy_pass http://inventory-service:8786/actuator/health;
  }

  location /payment-health {
    proxy_pass http://payment-service:8787/actuator/health;
  }

  location /order-health {
    proxy_pass http://order-service:8785/actuator/health;
  }

  location / {
    try_files $uri /index.html;
  }
}
